### ISSUE TITLE
Request to support 41256

### ISSUE THREAD

**Issue by iosoft** [trevor-makes/avr-dram-tester#1]
PLEASE PLEASE add support for **41256**.
My personal restoration work is pending due to a proper DRAM tester.

PLEASE.
![4116_4132_4164_41128_41256_power](https://user-images.githubusercontent.com/349968/226982773-7e56b139-f5ff-4448-98f2-5914036ca029.jpg)

**Comment by trevor-makes** [comment]
I just got some 41256 chips in the mail today, so I'll get started on this.

**Comment by iosoft** [comment]
> I just got some 41256 chips in the mail today, so I'll get started on this.

Pls share some pics.

**Comment by trevor-makes** [comment]
I added automatic detection for 41256 chips. The 41256 test takes significantly longer (around 9 seconds) so you can tell when that mode is running by the slower rate that the built-in LED blinks at.

I added a jumper from Arduino pin D9 (PB1) to DRAM pin 1 for the A8 address bit.

I tested with NEC D41256C-80, SL41256-10, MCM6665BP15 (4164), and KM4164B-12 chips.

Good luck with your restoration!

![41256](https://user-images.githubusercontent.com/86030837/227656198-c13352f0-4ddb-4703-9660-f7987383cb73.jpg)

**Comment by iosoft** [comment]
Can I build this on a Breadboard?

**Comment by trevor-makes** [comment]
You sure can! I made the first prototype on one before moving to a protoboard and it worked fine. The wiring isn't too complicated if you leave the wires long instead of cutting them just to length like I did below. It would be easier to use with a ZIF socket, but you could get away with plugging the DRAM directly into the breadboard. I'd also recommend just using a wire jumper instead of an SPST switch.

![](https://github.com/trevor-makes/avr-dram-tester/raw/main/images/breadboard.jpg)

**Comment by iosoft** [comment]
Yes, I will use Zif-socket.
Time to go to the Market :)

Keep up the good work.

**Comment by iosoft** [comment]
With your kind help and great work, I managed to build this awesome **41256 DRAM TESTER** for so cheap and fully effective.

I tested all my 54 ICs (KM41256AP-12), 10 found to be dead/bad.
Now, I can test ICs ordered from Aliexpress/eBay also.

![IMG20230329114020](https://user-images.githubusercontent.com/349968/228443365-f68ddd31-4c45-4d57-ae9e-6c42fd463b25.jpg)
